version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /spectro
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /spectro_bin
    schedule:
      interval: daily
      
