[package]
name = "spectro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.31.1", features = ["serde-serialize"] }
symm = { path = "/home/brent/Projects/symm" }
tensor = { path = "/home/brent/Projects/tensor" }
serde = { version = "1.0.144", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.85"
approx = "0.5.1"
summarize = { path = "/home/brent/Projects/summarize" }

[[bin]]
name = "prof"